# This files gather compiler flags that are common to g++, clang and
# pathCC

rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wall" "W" "Wshadow")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wpointer-arith" "Wcast-qual" "Wcast-align")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wwrite-strings" "Wctor-dtor-privacy" "Wnon-virtual-dtor")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Woverloaded-virtual" "Wreturn-type" "Wfloat-equal")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-endif-labels" "Wmissing-format-attribute")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-multichar" "Wno-deprecated-declarations" "Wpacked")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wredundant-decls")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wunknown-pragmas" "Wundef" "Wreorder")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-conversion")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wdouble-promotion")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winit-self")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-op")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-include-dirs")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnoexcept")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wold-style-cast")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wstrict-null-sentinel")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtrampolines")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wvector-operation-performance")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wignored-qualifiers")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsequence-point")
# rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=pure")
# rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=const")
# rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=noreturn")
# rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=format")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch-bool")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-not-parentheses")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsizeof-array-argument")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wbool-compare")
# rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winline")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wshift-negative-value")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wshift-overflow")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtautological-compare")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnull-dereference")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wduplicated-cond")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmisleading-indentation")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wduplicated-branches")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wregister")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wint-in-bool-context")
rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-override")

if(enable-developer-warnings)
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wextra")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "pedantic")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-compare")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-declarations")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wzero-as-null-pointer-constant")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-conversion")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-promo")
  if(NOT (WIN32 AND ( CMAKE_SIZEOF_VOID_P EQUAL 8 )))
    rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlong-long")
  endif(NOT (WIN32 AND ( CMAKE_SIZEOF_VOID_P EQUAL 8 )))
else(enable-developer-warnings)
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-switch-enum")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-covered-switch-default")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-covered-switch-default")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-sign-compare")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-missing-declarations")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-weak-vtables")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-unused-macros")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS
    "Wno-missing-variable-declarations")
endif(enable-developer-warnings)


if(enable-advanced-developer-warnings)
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-types")
  rsa_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-methods")
endif(enable-advanced-developer-warnings)
