# si fftw3 n'est pas installé dans un répertoire système il faut
# passer -DFFTW_INCLUDE_DIRS=.. et -DFFTW_LIBRARY_DIRS=.. en option de
# cmake

option(fft-use-longdouble "fft-use-longdouble" OFF)
option(fft-use-float "fft-use-float" OFF)
IF(fft-use-longdouble)
  MESSAGE("FFT Use long double")
  ADD_DEFINITIONS(-DTMFFT_USE_LONGDOUBLE)
ELSEIF(fft-use-float)
  MESSAGE("FFT Use float")
  ADD_DEFINITIONS(-DTMFFT_USE_FLOAT)
ENDIF(fft-use-longdouble)

FIND_PATH(FFTW_INCLUDE_DIR fftw3.h HINTS ${FFTW_INCLUDE_DIRS})
FIND_LIBRARY(FFTW_LIBRARY fftw3 HINTS ${FFTW_LIBRARY_DIRS} ${YAML_CPP_LIBRARIES})
FIND_LIBRARY(FFTW_OMP_LIBRARY fftw3_omp HINTS ${FFTW_LIBRARY_DIRS})


IF(FFTW_INCLUDE_DIR)
  MESSAGE(STATUS "FFTW_INCLUDE_DIR found")
ELSE(FFTW_INCLUDE_DIR)
  MESSAGE(STATUS "FFTW_INCLUDE_DIR not found")
ENDIF(FFTW_INCLUDE_DIR)

IF(FFTW_LIBRARY)
  MESSAGE(STATUS "FFTW_LIBRARY found")
ELSE(FFTW_LIBRARY)
  MESSAGE(STATUS "FFTW_LIBRARY not found")
ENDIF(FFTW_LIBRARY)

IF(FFTW_INCLUDE_DIR AND FFTW_LIBRARY)
  MESSAGE(STATUS "FFTW_INCLUDE_DIR=${FFTW_INCLUDE_DIR}")
  GET_FILENAME_COMPONENT(FFTW_LIBRARY "${FFTW_LIBRARY}" PATH)
  MESSAGE(STATUS "FFTW_LIBRARIES=${FFTW_LIBRARY}")
  ADD_DEFINITIONS("-DTMFFT_USE_FFTW3")
ELSE(FFTW_INCLUDE_DIR AND FFTW_LIBRARY)
  MESSAGE(FATAL_ERROR "fftw not found")
ENDIF(FFTW_INCLUDE_DIR AND FFTW_LIBRARY)

IF(FFTW_OMP_LIBRARY)
  MESSAGE(STATUS "fftw3_omp found")
  SET(HAVE_FFTW_OMP ON)
ELSE(FFTW_OMP_LIBRARY)
  MESSAGE(STATUS "fftw3_omp not found")
ENDIF(FFTW_OMP_LIBRARY)


# Test for Big Endian (VTK)
INCLUDE(TestBigEndian)
TEST_BIG_ENDIAN(BIGENDIAN)
IF(${BIGENDIAN})
  ADD_DEFINITIONS(-DBIGENDIAN)
ENDIF(${BIGENDIAN})

set (flags_FFTW)
IF(fft-use-longdouble)
	list(APPEND flags_FFTW "fftw3l")
ELSEIF(fft-use-float)
	list(APPEND flags_FFTW "fftw3f")
ELSE(fft-use-longdouble)
	list(APPEND flags_FFTW "fftw3")
ENDIF(fft-use-longdouble)
if(HAVE_FFTW_OMP)
  IF(fft-use-longdouble)
	  list(APPEND flags_FFTW "fftw3l_omp")
  ELSEIF(fft-use-float)
	  list(APPEND flags_FFTW "fftw3f_omp")
  ELSE(fft-use-longdouble)
	  list(APPEND flags_FFTW "fftw3_omp")
  ENDIF(fft-use-longdouble)
endif(HAVE_FFTW_OMP)
if(UNIX)
	list(APPEND flags_FFTW "dl")
endif(UNIX)
if(enable-slatec)
	list(APPEND flags_FFTW "slatec" "gfortran")
endif(enable-slatec)
list(APPEND flags_FFTW "lapack" "gfortran")

